### PR TITLE
fixed support for a custom-defined package names via option go_package

### LINKED ISSUE #63: Bug: support for a custom-defined package names via option go_package
When changing starwars example like this below:
```protobuf
...
option go_package = "github.com/ysugimoto/grpc-graphql-gateway/example/starwars/spec/starwars;starwarsv1";
...
```
Plugin will generate a file containing errors: it tries to access itself via `starwarsv1` import alias:
```
func Gql__type_ListHumansResponse() *graphql.Object {
...
			Fields: graphql.Fields{
				"humans": &graphql.Field{
					Type: graphql.NewList(starwarsv1.Gql__type_Character()),
                                                              ^^^^^^^^^^
				},
			},
...
	return gql__type_ListHumansResponse
}
```

### PR DESCRIPTION
**Pull request by qwerty-v**
Fixes #63

### CODE REVIEW

**Review by ysugimoto — COMMENTED** [review]
It seems fine but I'd like to see the result of the generated file using `{{ .FieldType $.RootPackage.Name }}`. I'm worrying about the package name should be fine and enabled to compile.

**Comment by qwerty-v** [comment]
@ysugimoto I've merged your master branch there as well. Also, I've included two commits: 
 - [ba7ab0c](https://github.com/ysugimoto/grpc-graphql-gateway/pull/66/commits/ba7ab0cd3513cc649e5db790a9a08b610bf824fd) predates any changes, it's just an ordinary `starwars` example fixed without any `go_package` changes talked about in #63.
 - [179c5f6](https://github.com/ysugimoto/grpc-graphql-gateway/pull/66/commits/179c5f612ecddb9f208fdeee60d8d22df6e5f433) however has the re-generated output with slightly modified `go_package` option, have a look.

Notably, the only real changes to the `starwars.graphql.go` are the `"github.com/graphql-go/graphql"`'s `Name` fields under it's type config. Earlier it was `Name: "Starwars_...` and now it is `Name: "Starwarsv1_...`.

**Comment by qwerty-v** [comment]
As for the compile-time errors, I haven't got any in the resulted output, though I haven't found the time to test it end-to-end. I do, however plan on opening another issue inspired by `grpc-gateway`'s project. In their project there's an utility called `protoc-gen-openapiv2`. I'm thinking doing the same for the `graphql` spec. The reason being is simple, it may be wiser to leverage the existing codebases to generate all the code for you, I'm talking about `gqlgen`. This project looks really promising compared to others and the only thing it needs is the `.graphql` schema files. Analogous to `protoc-gen-openapiv2`, having that generator for `graphql` schema will let you have the versatility with other existing, more prominent projects.

**Review by ysugimoto — APPROVED** [review]
Understood, thanks

**Comment by ysugimoto** [comment]
@qwerty-v This PR is ready to merge so could you please update the base branch? I can merge after that.

**Comment by qwerty-v** [comment]
@ysugimoto done

**Pull request merged**
